# Generated by Django 2.2.5 on 2019-09-24 19:19

from django.db import migrations

def create_data(apps,schema_editor):
    Customer = apps.get_model('customers','Customer')
    Customer(first_name="Customer 001",last_name="Customer 001", email="customer001@gmail.com",phone="0000000000",address="Customer 001 description").save()

class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
