# Generated by Django 2.2.6 on 2019-10-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20191019_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='box',
            field=models.TextField(blank=True, null=True),
        ),
    ]
