# Generated by Django 2.2.6 on 2019-10-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20191019_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='box',
        ),
        migrations.AddField(
            model_name='customer',
            name='text',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
    ]
