# Generated by Django 2.2.6 on 2019-10-19 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20191019_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Text'),
        ),
    ]
