# Generated by Django 2.2.6 on 2019-10-19 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20191019_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='text',
            new_name='box',
        ),
    ]
