# Generated by Django 2.2.6 on 2019-10-19 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20191019_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='box',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Text'),
        ),
    ]
