# Generated by Django 2.2.6 on 2019-10-19 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20191019_0603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['created']},
        ),
    ]
